version: '2'
services:
  configserver:
    image: johncarnell/tmx-confsvr:section12
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      #      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "exampledb20"
      MYSQL_DATABASE:       "exampledb"
  licensingservice:
    image: johncarnell/tmx-licensing-service:section12
    ports:
      - "8080:8080"
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "3306"
      ENCRYPT_KEY:       "IMSYMMETRIC"
